# config/params.yaml

# common base settings (shared by all profiles)
base:
  data:
    raw_path: data/raw
    interim_path: data/interim
    features_path: data/features
    external_path: data/external
    symbol: "ICICIBANK"
    index_symbols:
      - "NIFTY50"
    freq: "5min"
    prediction_horizon_bars: 12
    annualization_factor: 18900
    trading_hours:
      start: "09:15"
      end: "15:30"

  features:
    rolling_windows:
      short: 12
      medium: 75
      long: 375
    garch_like:
      squared_returns_window: 75
    intraday:
      include_time_of_day: true
      include_minutes_from_open: false
    price_measures:
      atr_window: 14
      high_low_window: 12
    cross_asset:
      include_index_volatility: true
      index_volatility_window: 75

  models:
    baseline: {}
    garch:
      p: 1
      q: 1
      dist: "normal"
      horizon: 12
      annualization_factor: 18900
      rolling_refit: false
      rolling_window: 2000
    ridge:
      alpha: 1.0
      random_state: 42
      max_iter: 10000
    lasso:
      alpha: 0.01
      random_state: 42
      max_iter: 10000
    random_forest:
      n_estimators: 200
      max_depth: 8
      min_samples_split: 5
      min_samples_leaf: 2
      random_state: 42
      n_jobs: -1
    xgboost:
      n_estimators: 300
      max_depth: 6
      learning_rate: 0.05
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
      n_jobs: -1

  evaluation:
    metrics:
      - rmse
      - mae
      - mape
    economic_utility:
      backtest:
        initial_capital: 1000000
        target_volatility: 0.02
        transaction_cost_bps: 5
        slippage_bps: 2
        fixed_cost: 0.0
        annualization_factor: 18900
        risk_free_rate: 0.05
        leverage_cap: 1.0
        max_position_size: 1.0
        min_position_size: 0.0
        allow_short: false
        save_equity_curve: true     # <-- default: save equity CSV
        save_equity_plot: true      # <-- default: save equity PNG plot

  output:
    figures_path: results/figures
    metrics_path: results/metrics
    backtest_path: results/backtest
    models_path: models

  run:
    random_seed: 42
    save_interim: true
    save_features: true
    parquet_engine: "pyarrow"

  options:
    use_xgboost_if_available: true
    require_arch_for_garch: true

# lightweight profile for quick dev / debugging (small windows, fewer models)
profiles:
  debug:
    data:
      symbol: "ICICIBANK_debug"
      prediction_horizon_bars: 6
    features:
      rolling_windows:
        short: 6
        medium: 30
        long: 150
    models:
      # train only baseline + ridge for quick iterations
      baseline: {}
      ridge:
        alpha: 1.0
        random_state: 42
        max_iter: 5000
    evaluation:
      economic_utility:
        backtest:
          save_equity_curve: true
          save_equity_plot: true
    run:
      save_interim: true
      save_features: true

  # full settings for production experiments
  production:
    data:
      symbol: "ICICIBANK"
      prediction_horizon_bars: 12
    features:
      rolling_windows:
        short: 12
        medium: 75
        long: 375
    models:
      baseline: {}
      garch:
        p: 1
        q: 1
        dist: "t"
        horizon: 12
        rolling_refit: false
        rolling_window: 5000
      ridge:
        alpha: 1.0
      lasso:
        alpha: 0.01
      random_forest:
        n_estimators: 400
        max_depth: 10
        n_jobs: -1
      xgboost:
        n_estimators: 500
        max_depth: 7
        learning_rate: 0.03
        n_jobs: -1
    evaluation:
      economic_utility:
        backtest:
          save_equity_curve: true
          save_equity_plot: true
    run:
      save_interim: true
      save_features: true
